// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxJNUwYOVDaqgXLXz_qsO0z5Yp28p5IAg',
    appId: '1:810360110683:web:cb7c4f94f6eb4f7962897e',
    messagingSenderId: '810360110683',
    projectId: 'food-delevery-86e84',
    authDomain: 'food-delevery-86e84.firebaseapp.com',
    storageBucket: 'food-delevery-86e84.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCX2FR0L_EgisFXMzjr0klSie5VsqyVMPU',
    appId: '1:810360110683:android:167e99f1ae49373662897e',
    messagingSenderId: '810360110683',
    projectId: 'food-delevery-86e84',
    storageBucket: 'food-delevery-86e84.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOw2yCZrlFiX3krqZBRz4EVdflmadwIvw',
    appId: '1:810360110683:ios:417a973ac926922c62897e',
    messagingSenderId: '810360110683',
    projectId: 'food-delevery-86e84',
    storageBucket: 'food-delevery-86e84.firebasestorage.app',
    iosBundleId: 'com.example.mvvmFolderStrucutre',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOw2yCZrlFiX3krqZBRz4EVdflmadwIvw',
    appId: '1:810360110683:ios:417a973ac926922c62897e',
    messagingSenderId: '810360110683',
    projectId: 'food-delevery-86e84',
    storageBucket: 'food-delevery-86e84.firebasestorage.app',
    iosBundleId: 'com.example.mvvmFolderStrucutre',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxJNUwYOVDaqgXLXz_qsO0z5Yp28p5IAg',
    appId: '1:810360110683:web:24ca0ae195d634ea62897e',
    messagingSenderId: '810360110683',
    projectId: 'food-delevery-86e84',
    authDomain: 'food-delevery-86e84.firebaseapp.com',
    storageBucket: 'food-delevery-86e84.firebasestorage.app',
  );
}
